import type { SupabaseClient } from '@supabase/supabase-js';
import type { UserMap } from './users';
import { EMPRESA_IDS } from './ids';
import { dayOffset, dateOffset } from './seed-date';

export async function seedCompanies(supabase: SupabaseClient, users: UserMap) {
  console.log('  Creating companies...');

  const empresas = [
    {
      id: EMPRESA_IDS.PETSHOP_MADRID,
      nombre: 'PetShop Madrid',
      lifecycle_stage: 'lead',
      fuente_lead: 'ads',
      vendedor_asignado: users.ignacio,
      proxima_accion: 'Llamar para presentar catalogo',
      proxima_accion_fecha: dateOffset(1),
      provincia: 'Madrid',
      etiquetas: ['premium', 'mascotas'],
      prioridad: 'alta',
      categoria: 'mascotas',
      descripcion: 'Tienda premium de mascotas en zona Salamanca',
      created_at: dayOffset(-12, 10),
      // Phase 10 — custom fields populated
      campos_personalizados: { cif: 'B-12345678', num_empleados: 8, es_cliente_vip: false },
    },
    {
      id: EMPRESA_IDS.VETPARTNERS,
      nombre: 'VetPartners Barcelona',
      lifecycle_stage: 'en_negociacion',
      fuente_lead: 'referido',
      vendedor_asignado: users.ignacio,
      proxima_accion: 'Enviar propuesta revisada',
      proxima_accion_fecha: dateOffset(-3),
      provincia: 'Barcelona',
      etiquetas: ['cadena', 'veterinaria', 'grande'],
      prioridad: 'alta',
      categoria: 'veterinaria',
      descripcion: 'Cadena de 3 clinicas veterinarias en Barcelona',
      informador: 'Dr. Martinez (cliente existente)',
      created_at: dayOffset(-27, 9),
      campos_personalizados: { cif: 'B-23456789', num_empleados: 42, es_cliente_vip: true },
    },
    {
      id: EMPRESA_IDS.AGROVET,
      nombre: 'AgroVet Levante',
      lifecycle_stage: 'contactado',
      fuente_lead: 'feria',
      vendedor_asignado: users.laura,
      proxima_accion: 'Enviar informacion de productos',
      proxima_accion_fecha: dateOffset(2),
      provincia: 'Valencia',
      etiquetas: ['agro', 'suministros'],
      prioridad: 'media',
      categoria: 'agro',
      descripcion: 'Distribuidor de suministros veterinarios para sector agro',
      created_at: dayOffset(-17, 11),
    },
    {
      id: EMPRESA_IDS.MASCOTAS_FELICES,
      nombre: 'Mascotas Felices',
      lifecycle_stage: 'cliente',
      fuente_lead: 'organico',
      vendedor_asignado: users.ignacio,
      provincia: 'Madrid',
      etiquetas: ['retail', 'multi-tienda'],
      prioridad: 'media',
      categoria: 'retail',
      descripcion: '2 tiendas de mascotas en Madrid centro',
      created_at: dayOffset(-32, 10),
    },
    {
      id: EMPRESA_IDS.PETFOOD_EXPRESS,
      nombre: 'PetFood Express',
      lifecycle_stage: 'lead',
      fuente_lead: 'cold_call',
      vendedor_asignado: users.laura,
      proxima_accion: 'Enviar catalogo por email',
      proxima_accion_fecha: dateOffset(3),
      provincia: 'Sevilla',
      etiquetas: ['alimentacion'],
      prioridad: 'baja',
      categoria: 'mascotas',
      descripcion: 'Tienda online de alimentacion para mascotas',
      created_at: dayOffset(-3, 14),
    },
    {
      id: EMPRESA_IDS.CLINICA_SOL,
      nombre: 'Clinica Veterinaria Sol',
      lifecycle_stage: 'en_negociacion',
      fuente_lead: 'referido',
      vendedor_asignado: users.laura,
      proxima_accion: 'Seguimiento propuesta enviada',
      proxima_accion_fecha: dateOffset(1),
      provincia: 'Madrid',
      etiquetas: ['clinica', 'grande'],
      prioridad: 'alta',
      categoria: 'veterinaria',
      descripcion: 'Clinica veterinaria grande con 15 empleados',
      informador: 'Dr. Torres (VetPartners)',
      created_at: dayOffset(-22, 9),
    },
    {
      id: EMPRESA_IDS.ANIMALIA,
      nombre: 'Animalia Store',
      lifecycle_stage: 'contactado',
      fuente_lead: 'bbdd',
      vendedor_asignado: users.ignacio,
      proxima_accion: 'Agendar reunion online',
      proxima_accion_fecha: dateOffset(4),
      provincia: 'Valencia',
      etiquetas: ['retail', 'mediana'],
      prioridad: 'media',
      categoria: 'retail',
      descripcion: 'Tienda mediana de mascotas en Valencia',
      created_at: dayOffset(-15, 10),
    },
    {
      id: EMPRESA_IDS.VETSALUD,
      nombre: 'VetSalud Plus',
      lifecycle_stage: 'lead',
      fuente_lead: 'ads',
      vendedor_asignado: users.laura,
      proxima_accion: 'Primera llamada de contacto',
      proxima_accion_fecha: dateOffset(1),
      provincia: 'Bilbao',
      etiquetas: ['veterinaria', 'startup'],
      prioridad: 'media',
      categoria: 'veterinaria',
      descripcion: 'Startup de telemedicina veterinaria',
      created_at: dayOffset(-5, 8),
    },
    {
      id: EMPRESA_IDS.PETCORNER,
      nombre: 'PetCorner Bilbao',
      lifecycle_stage: 'cliente',
      fuente_lead: 'referido',
      vendedor_asignado: users.ignacio,
      provincia: 'Bilbao',
      etiquetas: ['premium', 'fidelizado'],
      prioridad: 'alta',
      categoria: 'retail',
      descripcion: 'Tienda premium de mascotas en Bilbao. Cliente fidelizado.',
      created_at: dayOffset(-45, 10),
      campos_personalizados: { cif: 'B-34567890', num_empleados: 14, es_cliente_vip: true },
    },
    {
      id: EMPRESA_IDS.ZOORETAIL,
      nombre: 'ZooRetail Sevilla',
      lifecycle_stage: 'lead',
      fuente_lead: 'organico',
      vendedor_asignado: users.laura,
      proxima_accion: 'Contactar por telefono',
      proxima_accion_fecha: dateOffset(2),
      provincia: 'Sevilla',
      etiquetas: ['retail'],
      prioridad: 'baja',
      categoria: 'retail',
      descripcion: 'Pequeña tienda de animales en Sevilla',
      created_at: dayOffset(-2, 12),
    },
    {
      id: EMPRESA_IDS.NUTRIVET,
      nombre: 'Nutrivet Galicia',
      lifecycle_stage: 'no_interesa',
      fuente_lead: 'cold_call',
      vendedor_asignado: users.ignacio,
      provincia: 'A Coruna',
      etiquetas: ['suplementos'],
      prioridad: 'baja',
      categoria: 'agro',
      descripcion: 'Empresa de suplementos veterinarios. Sin presupuesto actualmente.',
      created_at: dayOffset(-36, 9),
    },
    // ===== Phase "Mock Data Overhaul" — coverage additions =====
    // ECOPETS — ex_cliente (churned), categoria 'servicios', fuente 'otro'
    {
      id: EMPRESA_IDS.ECOPETS,
      nombre: 'EcoPets Sostenible',
      lifecycle_stage: 'ex_cliente',
      fuente_lead: 'otro',
      vendedor_asignado: users.ignacio,
      proxima_accion: 'Llamada de reactivacion',
      proxima_accion_fecha: dateOffset(5),
      provincia: 'Zaragoza',
      etiquetas: ['eco', 'sostenible', 'reactivacion'],
      prioridad: 'media',
      categoria: 'servicios',
      descripcion: 'Cliente antiguo, cancelo hace 4 meses por cambio de proveedor. Reactivable.',
      informador: 'Ex-vendedor (contacto interno)',
      created_at: dayOffset(-90, 11),
    },
    // VETNORTE — categoria 'otro' coverage
    {
      id: EMPRESA_IDS.VETNORTE,
      nombre: 'VetNorte Asturias',
      lifecycle_stage: 'contactado',
      fuente_lead: 'feria',
      vendedor_asignado: users.laura,
      proxima_accion: 'Enviar muestras de producto',
      proxima_accion_fecha: dateOffset(6),
      provincia: 'Oviedo',
      etiquetas: ['veterinaria', 'rural'],
      prioridad: 'media',
      categoria: 'otro',
      descripcion: 'Asociacion de veterinarios rurales en Asturias',
      created_at: dayOffset(-10, 10),
    },
    // MASCOTAS_SUR — active lead, categoria mascotas, fuente bbdd
    {
      id: EMPRESA_IDS.MASCOTAS_SUR,
      nombre: 'Mascotas del Sur',
      lifecycle_stage: 'lead',
      fuente_lead: 'bbdd',
      vendedor_asignado: users.laura,
      proxima_accion: 'Primera llamada de prospeccion',
      proxima_accion_fecha: dateOffset(-1),
      provincia: 'Malaga',
      etiquetas: ['retail', 'nueva'],
      prioridad: 'media',
      categoria: 'mascotas',
      descripcion: 'Nueva tienda de mascotas en Malaga, abrio hace 2 meses',
      created_at: dayOffset(-7, 9),
    },
    // PETBOUTIQUE — cliente premium, categoria servicios
    {
      id: EMPRESA_IDS.PETBOUTIQUE,
      nombre: 'PetBoutique Luxury',
      lifecycle_stage: 'cliente',
      fuente_lead: 'organico',
      vendedor_asignado: users.ignacio,
      provincia: 'Madrid',
      etiquetas: ['lujo', 'premium', 'fidelizado'],
      prioridad: 'alta',
      categoria: 'servicios',
      descripcion: 'Boutique de lujo para mascotas en Madrid. Peluqueria y spa canino.',
      created_at: dayOffset(-60, 10),
      campos_personalizados: { cif: 'B-45678901', num_empleados: 6, es_cliente_vip: true },
    },
    // VETLAB — cliente (has won deal + lost deal in history)
    {
      id: EMPRESA_IDS.VETLAB,
      nombre: 'VetLab Diagnostico',
      lifecycle_stage: 'cliente',
      fuente_lead: 'referido',
      vendedor_asignado: users.laura,
      provincia: 'Valencia',
      etiquetas: ['laboratorio', 'diagnostico', 'mediano'],
      prioridad: 'media',
      categoria: 'veterinaria',
      descripcion: 'Laboratorio de diagnostico veterinario. Cerro primera compra, segunda propuesta perdida.',
      informador: 'Dra. Moreno (Clinica Sol)',
      created_at: dayOffset(-80, 10),
    },
  ];

  // `campos_personalizados` is NOT NULL on all three Phase 10 tables.
  // Supabase's bulk upsert sends every key from every row (missing → null),
  // so rows without an explicit value need an empty-object default injected here.
  const rows = empresas.map((e) => ({ campos_personalizados: {}, ...e }));
  const { error } = await supabase.from('empresas').upsert(rows);
  if (error) throw new Error(`Companies: ${error.message}`);
}
