import type { SupabaseClient } from '@supabase/supabase-js';
import type { UserMap } from './users';
import { EMPRESA_IDS } from './ids';

export async function seedCompanies(supabase: SupabaseClient, users: UserMap) {
  console.log('  Creating companies...');

  const empresas = [
    {
      id: EMPRESA_IDS.PETSHOP_MADRID,
      nombre: 'PetShop Madrid',
      lifecycle_stage: 'lead',
      fuente_lead: 'ads',
      vendedor_asignado: users.ignacio,
      proxima_accion: 'Llamar para presentar catalogo',
      proxima_accion_fecha: '2026-04-07',
      provincia: 'Madrid',
      etiquetas: ['premium', 'mascotas'],
      prioridad: 'alta',
      categoria: 'mascotas',
      descripcion: 'Tienda premium de mascotas en zona Salamanca',
      created_at: '2026-03-25T10:00:00Z',
    },
    {
      id: EMPRESA_IDS.VETPARTNERS,
      nombre: 'VetPartners Barcelona',
      lifecycle_stage: 'en_negociacion',
      fuente_lead: 'referido',
      vendedor_asignado: users.ignacio,
      proxima_accion: 'Enviar propuesta revisada',
      proxima_accion_fecha: '2026-04-03',
      provincia: 'Barcelona',
      etiquetas: ['cadena', 'veterinaria', 'grande'],
      prioridad: 'alta',
      categoria: 'veterinaria',
      descripcion: 'Cadena de 3 clinicas veterinarias en Barcelona',
      informador: 'Dr. Martinez (cliente existente)',
      created_at: '2026-03-10T09:00:00Z',
    },
    {
      id: EMPRESA_IDS.AGROVET,
      nombre: 'AgroVet Levante',
      lifecycle_stage: 'contactado',
      fuente_lead: 'feria',
      vendedor_asignado: users.laura,
      proxima_accion: 'Enviar informacion de productos',
      proxima_accion_fecha: '2026-04-08',
      provincia: 'Valencia',
      etiquetas: ['agro', 'suministros'],
      prioridad: 'media',
      categoria: 'agro',
      descripcion: 'Distribuidor de suministros veterinarios para sector agro',
      created_at: '2026-03-20T11:00:00Z',
    },
    {
      id: EMPRESA_IDS.MASCOTAS_FELICES,
      nombre: 'Mascotas Felices',
      lifecycle_stage: 'cliente',
      fuente_lead: 'organico',
      vendedor_asignado: users.ignacio,
      provincia: 'Madrid',
      etiquetas: ['retail', 'multi-tienda'],
      prioridad: 'media',
      categoria: 'retail',
      descripcion: '2 tiendas de mascotas en Madrid centro',
      created_at: '2026-03-05T10:00:00Z',
    },
    {
      id: EMPRESA_IDS.PETFOOD_EXPRESS,
      nombre: 'PetFood Express',
      lifecycle_stage: 'lead',
      fuente_lead: 'cold_call',
      vendedor_asignado: users.laura,
      proxima_accion: 'Enviar catalogo por email',
      proxima_accion_fecha: '2026-04-09',
      provincia: 'Sevilla',
      etiquetas: ['alimentacion'],
      prioridad: 'baja',
      categoria: 'mascotas',
      descripcion: 'Tienda online de alimentacion para mascotas',
      created_at: '2026-04-03T14:00:00Z',
    },
    {
      id: EMPRESA_IDS.CLINICA_SOL,
      nombre: 'Clinica Veterinaria Sol',
      lifecycle_stage: 'en_negociacion',
      fuente_lead: 'referido',
      vendedor_asignado: users.laura,
      proxima_accion: 'Seguimiento propuesta enviada',
      proxima_accion_fecha: '2026-04-07',
      provincia: 'Madrid',
      etiquetas: ['clinica', 'grande'],
      prioridad: 'alta',
      categoria: 'veterinaria',
      descripcion: 'Clinica veterinaria grande con 15 empleados',
      informador: 'Dr. Torres (VetPartners)',
      created_at: '2026-03-15T09:00:00Z',
    },
    {
      id: EMPRESA_IDS.ANIMALIA,
      nombre: 'Animalia Store',
      lifecycle_stage: 'contactado',
      fuente_lead: 'bbdd',
      vendedor_asignado: users.ignacio,
      proxima_accion: 'Agendar reunion online',
      proxima_accion_fecha: '2026-04-10',
      provincia: 'Valencia',
      etiquetas: ['retail', 'mediana'],
      prioridad: 'media',
      categoria: 'retail',
      descripcion: 'Tienda mediana de mascotas en Valencia',
      created_at: '2026-03-22T10:00:00Z',
    },
    {
      id: EMPRESA_IDS.VETSALUD,
      nombre: 'VetSalud Plus',
      lifecycle_stage: 'lead',
      fuente_lead: 'ads',
      vendedor_asignado: users.laura,
      proxima_accion: 'Primera llamada de contacto',
      proxima_accion_fecha: '2026-04-07',
      provincia: 'Bilbao',
      etiquetas: ['veterinaria', 'startup'],
      prioridad: 'media',
      categoria: 'veterinaria',
      descripcion: 'Startup de telemedicina veterinaria',
      created_at: '2026-04-01T08:00:00Z',
    },
    {
      id: EMPRESA_IDS.PETCORNER,
      nombre: 'PetCorner Bilbao',
      lifecycle_stage: 'cliente',
      fuente_lead: 'referido',
      vendedor_asignado: users.ignacio,
      provincia: 'Bilbao',
      etiquetas: ['premium', 'fidelizado'],
      prioridad: 'alta',
      categoria: 'retail',
      descripcion: 'Tienda premium de mascotas en Bilbao. Cliente fidelizado.',
      created_at: '2026-02-20T10:00:00Z',
    },
    {
      id: EMPRESA_IDS.ZOORETAIL,
      nombre: 'ZooRetail Sevilla',
      lifecycle_stage: 'lead',
      fuente_lead: 'organico',
      vendedor_asignado: users.laura,
      proxima_accion: 'Contactar por telefono',
      proxima_accion_fecha: '2026-04-08',
      provincia: 'Sevilla',
      etiquetas: ['retail'],
      prioridad: 'baja',
      categoria: 'retail',
      descripcion: 'Pequeña tienda de animales en Sevilla',
      created_at: '2026-04-04T12:00:00Z',
    },
    {
      id: EMPRESA_IDS.NUTRIVET,
      nombre: 'Nutrivet Galicia',
      lifecycle_stage: 'no_interesa',
      fuente_lead: 'cold_call',
      vendedor_asignado: users.ignacio,
      provincia: 'A Coruna',
      etiquetas: ['suplementos'],
      prioridad: 'baja',
      categoria: 'agro',
      descripcion: 'Empresa de suplementos veterinarios. Sin presupuesto actualmente.',
      created_at: '2026-03-01T09:00:00Z',
    },
  ];

  const { error } = await supabase.from('empresas').upsert(empresas);
  if (error) throw new Error(`Companies: ${error.message}`);
}
