import type { SupabaseClient } from '@supabase/supabase-js';
import type { UserMap } from './users';
import { FASE_IDS } from './ids';

export async function seedScripts(supabase: SupabaseClient, users: UserMap) {
  console.log('  Creating scripts...');

  const scripts = [
    {
      titulo: 'Llamada en frio - Apertura completa',
      fase_asociada: FASE_IDS.NUEVO_LEAD,
      contenido: [
        '1) APERTURA (15 segundos):',
        'Hola [NOMBRE], le llamo de [EMPRESA]. Se que no me esperaba, asi que ire al grano. Mi nombre es [VENDEDOR] y trabajamos con tiendas y distribuidores como el suyo en [PROVINCIA].',
        '',
        '2) RAZON DE LA LLAMADA:',
        'Le llamo porque hemos ayudado a negocios similares al suyo a aumentar el ticket medio un 18-25% sustituyendo dos o tres referencias de su catalogo actual por nuestra gama premium, sin tocar el resto del surtido.',
        '',
        '3) PERMISO PARA CONTINUAR:',
        'Tiene dos minutos para que le explique como funciona y vemos si tiene sentido para usted? Si no encaja, se lo digo yo mismo y no le hago perder mas tiempo.',
        '',
        '4) PREGUNTAS DE CALIFICACION (si dice que si):',
        '- Cuantas referencias maneja actualmente en su categoria principal?',
        '- Quien le sirve hoy esos productos?',
        '- Cuando fue la ultima vez que renovo el catalogo?',
        '',
        '5) OBJECION "ESTOY OCUPADO":',
        'Le entiendo perfectamente, no le robo mas de 30 segundos. Le mando un email con tres ejemplos concretos de tiendas como la suya y, si le interesa lo que ve, me llama usted. Le parece?',
        '',
        '6) CIERRE DE LA LLAMADA:',
        'Genial. Le bloqueo 20 minutos en mi agenda el [FECHA] a las [HORA]? Le envio invitacion de calendario ahora mismo y un par de fichas de producto para que vaya viendo. Confirmamos por email?',
      ].join('\n'),
      tags: ['apertura', 'prospeccion', 'frio'],
      created_by: users.rebeca,
    },
    {
      titulo: 'Seguimiento de propuesta',
      fase_asociada: FASE_IDS.PROPUESTA,
      contenido: [
        '1) APERTURA:',
        'Buenos dias [NOMBRE], soy [VENDEDOR] de [EMPRESA]. Le llamo para hacer seguimiento de la propuesta que le envie el [FECHA] sobre [ASUNTO]. Como le va la semana?',
        '',
        '2) PREGUNTA ABIERTA:',
        'Ha tenido oportunidad de revisarla con calma? Cual es su primera impresion?',
        '',
        '3) SI YA LA HA VISTO:',
        '- Que parte le ha encajado mejor?',
        '- Hay algun apartado que le haya generado dudas o que quiera que repasemos juntos?',
        '- Esta lo que esperaba en cuanto a alcance y plazos?',
        '',
        '4) SI AUN NO LA HA VISTO:',
        'Sin problema, lo entiendo. Le propongo una cosa: bloqueamos 20 minutos manana o pasado y la repasamos juntos por videollamada. Asi resolvemos cualquier duda en directo y usted no tiene que invertir tiempo leyendola en frio. Que prefiere, manana a las 11 o pasado a las 16?',
        '',
        '5) PREGUNTA CLAVE PARA AVANZAR:',
        'Si os encaja todo lo que hemos planteado, hay algun tramite interno (comite, aprobacion de direccion, validacion tecnica) que tengamos que prever para no perder tiempo despues?',
        '',
        '6) PROXIMO PASO CONCRETO:',
        'Perfecto. Lo dejamos asi: yo le envio hoy mismo [DOCUMENTO/AJUSTE] y nos volvemos a hablar el [FECHA]. Le parece bien que lo bloquee en agenda ahora?',
      ].join('\n'),
      tags: ['seguimiento', 'propuesta', 'cierre'],
      created_by: users.rebeca,
    },
    {
      titulo: 'Negociacion de precios y objeciones',
      fase_asociada: FASE_IDS.NEGOCIACION,
      contenido: [
        '1) RECONOCER LA OBJECION SIN CEDER:',
        'Entiendo perfectamente, [NOMBRE]. El precio es importante y es normal que lo cuestione. Antes de hablar de numeros, me gustaria asegurarme de que estamos comparando lo mismo.',
        '',
        '2) REENMARCAR EL VALOR:',
        'Recordemos que el precio incluye [VALOR_DIFERENCIAL_1], [VALOR_DIFERENCIAL_2] y [VALOR_DIFERENCIAL_3]. La mayoria de nuestros clientes recuperan la inversion en los primeros [N] meses solo con [METRICA].',
        '',
        '3) PREGUNTA DIAGNOSTICA:',
        '- Con que precio o competidor lo esta comparando?',
        '- Que le falta a esta propuesta para que sea un "si" claro?',
        '- Es solo el precio o hay algun otro punto que tambien le frene?',
        '',
        '4) ESCALERA DE CONCESIONES (no usar todas a la vez):',
        '- Opcion A: Mantener el precio y anadir [SERVICIO_EXTRA] sin coste.',
        '- Opcion B: Plan de pago en dos veces (50% al firmar, 50% a 30 dias).',
        '- Opcion C: 5% de descuento si cerramos antes del [FECHA_LIMITE] y firmamos por 12 meses.',
        '- Opcion D: 7% si ademas confirmamos pedido inicial minimo de [IMPORTE].',
        '',
        '5) PEDIR ALGO A CAMBIO (siempre):',
        'Puedo aplicar el descuento, pero a cambio necesito que cerremos esta misma semana y que firmemos por 12 meses. Le encaja?',
        '',
        '6) CIERRE CONDICIONAL:',
        'Si le aplico [CONCESION], tenemos acuerdo hoy? Le envio el contrato firmado por mi parte en cuanto colguemos.',
      ].join('\n'),
      tags: ['negociacion', 'cierre', 'descuento', 'objeciones'],
      created_by: users.rebeca,
    },
    {
      titulo: 'Bienvenida y onboarding nuevo cliente',
      fase_asociada: FASE_IDS.POSTVENTA,
      contenido: [
        '1) MENSAJE DE BIENVENIDA (mismo dia del cierre):',
        'Bienvenido a bordo, [NOMBRE]! Acaba de tomar una gran decision y quiero asegurarme de que el arranque sea impecable. Soy [VENDEDOR] y voy a ser su contacto principal durante los proximos 90 dias.',
        '',
        '2) PROXIMOS PASOS CONCRETOS:',
        '- Hoy: confirmacion de pedido y factura proforma por email.',
        '- En 24 horas: alta en nuestro portal de cliente con sus credenciales.',
        '- En 48 horas: llamada de bienvenida con [GESTOR_CUENTA] para presentaciones.',
        '- En 7 dias: primera entrega segun el calendario acordado.',
        '- En 14 dias: revision de stock y ajustes si es necesario.',
        '',
        '3) RECORDAR EL POR QUE:',
        'Recuerde que el objetivo que nos marcamos era [OBJETIVO_CLIENTE]. Vamos a medirlo cada mes y lo revisaremos juntos en nuestra reunion del [FECHA].',
        '',
        '4) CHECK-IN A LOS 30 DIAS (agendar ya):',
        'Le bloqueo 30 minutos en agenda el [FECHA] para revisar como ha ido el primer mes, ajustar lo que haga falta y planificar el siguiente. Le mando invitacion ahora.',
        '',
        '5) INVITACION A REFERENCIA (a partir del dia 60):',
        'Si todo va como esperamos, en un par de meses me gustaria pedirle una referencia. No le robaria mas de 5 minutos: solo una llamada con un cliente potencial parecido a usted. Le parece bien que se lo plantee mas adelante?',
        '',
        '6) CIERRE EMOCIONAL:',
        'Mi telefono directo es [TELEFONO] y mi email [EMAIL]. Para cualquier cosa, me llama directamente a mi. Bienvenido al equipo, [NOMBRE]!',
      ].join('\n'),
      tags: ['onboarding', 'cliente', 'postventa', 'fidelizacion'],
      created_by: users.rebeca,
    },
  ];

  const { error } = await supabase.from('scripts').upsert(scripts, { onConflict: 'id' });
  if (error) throw new Error(`Scripts: ${error.message}`);
}
